config/routes.rb
Rails.application.routes.draw do

  resources :coupons
  get 'home/index'
  devise_for :users
  resources :items do
  	resource :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user, optional: true
	has_many :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items

  def subscribed?
  	stripe_subscription_id?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

  
    respond_to do |format|
      if @coupon.save

        # Stripe counpon creation
        coupon = Stripe::Coupon.create({
          duration: coupon_params[:duration],
          id: coupon_params[:name],
          percent_off: coupon_params[:percent_off],
        })
        
        format.html { redirect_to @coupon, notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:duration, :name, :percent_off)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    respond_to do |format|
      if @item.save

        #################################################
        #################################################
        #################################################
        # if you want to create new stripe plan on every new item creation in rail app.
        # you can use below code. 
        #################################################
        #################################################
        #################################################

        # Stripe::Plan.create({
        #   amount: params['item']['price']*100,
        #   interval: 'month',
        #   product: {
        #     name: params['item']['name'],
        #   },
        #   currency: 'usd',
        #   id: @item.id,
        # })

        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_action :authenticate_user!, except: [:new]
	before_action :redirect_to_signup, only: [:new]

	def show
	end

	def new
		@quantity = params[:quantity]
		@coupon_name = params[:coupon_name].present? ? params[:coupon_name] : ""
	end

	def create
		#################################
		#################################
		#################################
		# Main logic of stripe subscription handled in this code
		# First i am finding the subscription already subscribed or not
		# and then subscribing based on the quantity entered in form field
		#################################
		#################################
		#################################

		customer = if current_user.stripe_id?
					Stripe::Customer.retrieve(current_user.stripe_id)
				else
					if stripe_plan.present?
						Stripe::Customer.create(
							email: current_user.email,
							source: params[:stripeToken])
					end
				end

		subscription = customer.subscriptions.create(
			plan: stripe_plan.id.to_sym,
			quantity: params[:quantity],
			coupon: params[:coupon_name].present? ? params[:coupon_name]: ""
		)
		
		current_user.update(
			stripe_id: customer.id,
			stripe_subscription_id: subscription.id,
			card_last4: params[:card_last4],
			card_exp_month: params[:card_exp_month],
			card_exp_year: params[:card_exp_year],
			card_type: params[:card_brand]
		)
		redirect_to root_path
	end



	def destroy
		if stripe_subscription.present?
			Stripe::Subscription.delete(stripe_subscription.id.to_sym)
			current_user.update(
			stripe_id: nil,
			stripe_subscription_id: nil,
			card_last4: nil,
			card_exp_month: nil,
			card_exp_year: nil,
			card_type: nil
			)
		redirect_to root_path
		end
	end

	private

		def stripe_plan
			stripe_plan ||= Stripe::Plan.retrieve("vessel")
		end

		def stripe_subscription
			stripe_subscription ||= Stripe::Subscription.retrieve(current_user.stripe_subscription_id)
		end 

		def redirect_to_signup
			if !user_signed_in?
				session["user_return_to"] = new_subscription_path
				redirect_to new_user_registration_path
			end	
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user_subscribed?
		user_signed_in? && current_user.subscribed?
	end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/coupons/_form.html.erb
<%= form_with(model: coupon, local: true) do |form| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :percent_off %>
    <%= form.number_field :percent_off %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Duration</th>
      <th>Name</th>
      <th>Percent off</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.duration %></td>
        <td><%= coupon.name %></td>
        <td><%= coupon.percent_off %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duration:</strong>
  <%= @coupon.duration %>
</p>

<p>
  <strong>Name:</strong>
  <%= @coupon.name %>
</p>

<p>
  <strong>Percent off:</strong>
  <%= @coupon.percent_off %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>

app/views/home/index.html.erb
<h1>Stripe Integration</h1>


<div class="row">
  	<%@items.each do |item|%>
	  <div class="col-sm-6">
	    <div class="card">
	      <div class="card-body">
	        <h3><%=item.name%></h3>
	        <p><strong>Price</strong>: <%=item.price%></p>
	        <p class="card-text"><%=item.description%></p>
	        <%if current_user_subscribed?%>
	        	<h3>subscribed..</h3>
	        	<%= link_to "Unsubscribe", item_subscriptions_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
	        <%else%>
	        	<%= form_tag new_item_subscriptions_path(item), method: :get do %>
				  	<label>Coupon Code</label>
				  	<%= text_field_tag :coupon_name %><br>
				  	<label for="quantity">Quantity</label>
					<%= text_field_tag :quantity %>
					<br>
					<%= submit_tag "Submit", class: "btn btn-primary" %>
				<% end %>
	        <% end %>
	      </div>
	    </div>
	    <br>
	  </div>
	<%end%>
</div>

<br><br>
<%= link_to "My Items", items_path, class: "btn btn-primary" %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%if current_user_subscribed?%>
	<h1>Enjoy your Subscription...</h1>
<%else%>
	<%= link_to "Subscribe To Watch", new_subscription_path, class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC%>
  </head>

  <body>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn btn-primary' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-danger'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>


    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subscriptions/new.html.erb
<!-- <script src="https://js.stripe.com/v3/"></script> -->

<%= form_tag item_subscriptions_path, id: "payment-form" do%>
  <div>
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>
    <%= hidden_field_tag :quantity, @quantity %>
    <%= hidden_field_tag :coupon_name, @coupon_name %>
    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
<% end %>


<style type="text/css">
  /**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}
</style>


<script type="text/javascript">
// Main JS which is provided by stripe to create form


// Create a Stripe client.
var stripe = Stripe($("meta[name='stripe-key']").attr("content"));
// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});
console.log(card);
// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'card_last4');
  hiddenInput.setAttribute('value', token.card.last4);
  form.appendChild(hiddenInput);

  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'card_exp_month');
  hiddenInput.setAttribute('value', token.card.exp_month);
  form.appendChild(hiddenInput);

  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'card_exp_year');
  hiddenInput.setAttribute('value', token.card.exp_year);
  form.appendChild(hiddenInput);

  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'card_brand');
  hiddenInput.setAttribute('value', token.card.brand);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>

app/views/subscriptions/show.html.erb
<h1>subscribe!</h1>